# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

pool: local

stages:
- stage: Test
  displayName: 'Test Stage'
  jobs:
    
  - job: Checkmarx_Scan
    displayName: 'Checkmarkjob'
    steps:
    - script: echo "Checkmarx Scan"
      displayName: 'Checmarxscript'



- stage: Deploy
  displayName: 'DeployStage'
  jobs:
  - job: Production_Deploy
    displayName: 'DeployJob'
    steps:
    - script: echo "Production Deploy"
